github_url: https://github.com
mainPageUrl: https://example.com

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "team_members"
    values:
      layout: "team_member"

collections:
  team_members:
    output: true