trigger:
 branches:
     include:
         - "main"
 paths:
     include:
         - "/aws/codedeploy/app"

pr: none

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"