# Schema: https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json

trigger: none
pr: none

# This is just an example, there would most likely be other steps involved, like variable 
# substitution, file zipping, and pre-release approvals (possibly).
steps:
- task: CodeDeployDeployApplication@1
  displayName: 'Deploy with CodeDeploy: TestingAwsCodeDeploy'
  inputs:
    awsCredentials: 'AWS Code Deploy'
    regionName: 'us-east-1'
    applicationName: TestingAwsCodeDeploy
    deploymentGroupName: TestingAgain
    revisionBundle: '$(System.DefaultWorkingDirectory)/aws/codedeploy/app'
    bucketName: testingcodedeploy1245
    fileExistsBehavior: OVERWRITE