name: Build and Deploy MutliArch Dockerfile Example

on:
  push:
    paths:
      - 'github/actions/**'

env:
  DOCKERHUB_USERNAME: trfc

jobs:
  build:
    name: build 
    runs-on: ubuntu-latest

    # https://github.com/docker/build-push-action#path-context
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./github/actions/ 
          file: github/actions/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
          push: true
          tags: |
            trfc/actiontest